#include "Actor/Gimmick/LCAutoGimmick.h"
#include "TimerManager.h"
#include "LastCanary.h"

ALCAutoGimmick::ALCAutoGimmick()
	: bStartAtBeginPlay(false)
	, bLoopingEnabled(false)
	, LoopInterval(0.f)
	, LoopType(EGimmickLoopType::None)
	, ForwardMoveDuration(1.0f)
	, BackwardMoveDuration(1.0f)
	, ForwardRotationDuration(1.0f)
	, BackwardRotationDuration(1.0f)
{
	ActivationType = EGimmickActivationType::ActivateOnConditionMet;
	bToggleState = false;
	bUseAlternateToggle = false;
}

void ALCAutoGimmick::BeginPlay()
{
	Super::BeginPlay();

	if (HasAuthority() && bStartAtBeginPlay && LoopType != EGimmickLoopType::None)
	{
		GetWorldTimerManager().SetTimer(LoopTimerHandle, this, &ALCAutoGimmick::StartLoop, 3.0f, false);
	}
}

void ALCAutoGimmick::StartLoop()
{
	if (!HasAuthority()) return;

	//LOG_Art(Log, TEXT("â–¶ [StartLoop] ë£¨í”„ ì‹œì‘"));

	bLoopingEnabled = true;
	HandleLoop();
}

void ALCAutoGimmick::StopLoop()
{
	if (!HasAuthority()) return;

	bLoopingEnabled = false;
	GetWorldTimerManager().ClearTimer(LoopTimerHandle);
}

void ALCAutoGimmick::HandleLoop()
{
	if (!HasAuthority() || !bLoopingEnabled || LoopType == EGimmickLoopType::None)
		return;

	//LOG_Art(Log, TEXT("[HandleLoop] ë£¨í”„ ì‹¤í–‰ - íƒ€ì…: %d"), static_cast<int32>(LoopType));

	if (IsGimmickBusy_Implementation())
	{
		GetWorldTimerManager().SetTimer(LoopTimerHandle, this, &ALCAutoGimmick::HandleLoop, 0.1f, false);
		return;
	}

	switch (LoopType)
	{
	case EGimmickLoopType::LoopForward:
	{
		LOG_Art(Log, TEXT("[HandleLoop] LoopForward - íšŒì „ ìƒíƒœ ì´ˆê¸°í™” ë° ì‹¤í–‰"));

		bUseAlternateToggle = false;

		CurrentRotationQuat = VisualMesh->GetComponentQuat();
		OriginalRotationQuat = CurrentRotationQuat;
		InitialRotation = CurrentRotationQuat;

		StartMovement();
		StartRotation();
		break;
	}

	case EGimmickLoopType::PingPong:
	{
		//LOG_Art(Log, TEXT("[HandleLoop] PingPong - ActivateGimmick í˜¸ì¶œ"));

		bUseAlternateToggle = true;

		if (OriginalRotationQuat.Equals(FQuat::Identity, 0.01f))
		{
			OriginalRotationQuat = VisualMesh->GetComponentQuat();
			CurrentRotationQuat = OriginalRotationQuat;
			RotationIndex = 0; 

			//LOG_Art(Log, TEXT("âœ… ìµœì´ˆ íšŒì „ ìƒíƒœ ì €ì¥ë¨: %s"), *OriginalRotationQuat.Rotator().ToCompactString());
		}
		
		ILCGimmickInterface::Execute_ActivateGimmick(this);
		break;
	}



	default:
		break;
	}
}

void ALCAutoGimmick::ScheduleNextLoop()
{
	//LOG_Art(Log, TEXT("ğŸ”„ [ScheduleNextLoop] í˜¸ì¶œë¨ - Interval: %.2f"), LoopInterval);

	if (!HasAuthority() || !bLoopingEnabled) return;

	if (LoopInterval <= 0.f)
	{
		//LOG_Art(Log, TEXT("â–¶ [ScheduleNextLoop] ì¦‰ì‹œ HandleLoop í˜¸ì¶œ"));
		HandleLoop();
	}
	else
	{
		//LOG_Art(Log, TEXT("â–¶ [ScheduleNextLoop] íƒ€ì´ë¨¸ë¡œ HandleLoop ì˜ˆì•½"));
		GetWorldTimerManager().SetTimer(LoopTimerHandle, this, &ALCAutoGimmick::HandleLoop, LoopInterval, false);
	}
}

void ALCAutoGimmick::ActivateGimmick_Implementation()
{
	if (!HasAuthority()) return;
	if (!ILCGimmickInterface::Execute_CanActivate(this)) return;

	//LOG_Art(Log, TEXT("â–¶ [ActivateGimmick] ì‹¤í–‰"));

	if (LoopType == EGimmickLoopType::PingPong)
	{
		if (RotationIndex == 0)
		{
			CacheOriginalRotation();
		}

		const bool bIsForward = (RotationIndex % 2 == 0);

		//LOG_Art(Log, TEXT("[ActivateGimmick] PingPong - ë°©í–¥: %s"), bIsForward ? TEXT("Forward") : TEXT("Backward"));

		MoveDuration = bIsForward ? ForwardMoveDuration : BackwardMoveDuration;
		RotationDuration = bIsForward ? ForwardRotationDuration : BackwardRotationDuration;

		if (!MoveVector.IsNearlyZero())
		{
			const FVector BaseMoveVector = MoveVector.GetSafeNormal() * MoveVector.Size();
			MoveVector = bIsForward ? BaseMoveVector : -BaseMoveVector;
		}

		if (bIsForward)
		{
			InitialRotation = OriginalRotationQuat;
			const FVector Axis = GetRotationAxisVector(RotationAxisEnum);
			const float AngleRad = FMath::DegreesToRadians(RotationAngle * RotationCount);
			const FQuat DeltaQuat = FQuat(Axis, AngleRad);
			TargetRotation = DeltaQuat * InitialRotation;
			CurrentRotationQuat = TargetRotation;
		}
		else
		{
			InitialRotation = CurrentRotationQuat;
			TargetRotation = OriginalRotationQuat;
			CurrentRotationQuat = TargetRotation;
		}

		RotationIndex++;
	}

	Super::ActivateGimmick_Implementation();
}
void ALCAutoGimmick::DeactivateGimmick_Implementation()
{
	if (!HasAuthority()) return;

	StopLoop();
	Super::DeactivateGimmick_Implementation();
}

void ALCAutoGimmick::CompleteMovement()
{
	//LOG_Art(Log, TEXT("âœ”ï¸ [CompleteMovement] ì´ë™ ì™„ë£Œ"));

	const bool bShouldReturn = !bLoopingEnabled && !bToggleState;

	if (bShouldReturn)
	{
		//LOG_Art(Log, TEXT("â–¶ [CompleteMovement] ë³µê·€ ì˜ˆì•½"));
		Super::CompleteMovement();
	}
	else
	{
		SetActorLocation(TargetLocation);
		bIsMovingServer = false;
	}

	// âœ… ë£¨í”„ ì²˜ë¦¬
	if (bLoopingEnabled)
	{
		if (LoopInterval > 0.f)
		{
			GetWorldTimerManager().SetTimer(LoopTimerHandle, this, &ALCAutoGimmick::HandleLoop, LoopInterval, false);
		}
		else
		{
			HandleLoop(); // ì¦‰ì‹œ ë°˜ë³µ
		}
	}
}

void ALCAutoGimmick::CompleteRotation()
{
	//LOG_Art(Log, TEXT("âœ”ï¸ [CompleteRotation] íšŒì „ ì™„ë£Œ"));

	const bool bShouldReturn = !bLoopingEnabled && !bToggleState;

	if (bShouldReturn)
	{
		LOG_Art(Log, TEXT("â–¶ [CompleteRotation] ë³µê·€ ì˜ˆì•½"));
		Super::CompleteRotation();
	}
	else
	{
		VisualMesh->SetWorldRotation(TargetRotation);
		bIsRotatingServer = false;
	}

	// âœ… ë£¨í”„ ì²˜ë¦¬
	if (bLoopingEnabled)
	{
		if (LoopInterval > 0.f)
		{
			GetWorldTimerManager().SetTimer(LoopTimerHandle, this, &ALCAutoGimmick::HandleLoop, LoopInterval, false);
		}
		else
		{
			HandleLoop(); // ì¦‰ì‹œ ë°˜ë³µ
		}
	}
}

void ALCAutoGimmick::CompleteReturn()
{
	//LOG_Art(Log, TEXT("âœ… [CompleteReturn] ë³µê·€ ì´ë™ ì™„ë£Œ"));
	Super::CompleteReturn();

	if (LoopType == EGimmickLoopType::PingPong && bLoopingEnabled)
	{
		if (LoopInterval > 0.f)
		{
			GetWorldTimerManager().SetTimer(LoopTimerHandle, this, &ALCAutoGimmick::HandleLoop, LoopInterval, false);
		}
		else
		{
			HandleLoop();
		}
	}
}

void ALCAutoGimmick::CompleteRotationReturn()
{
	//LOG_Art(Log, TEXT("âœ… [CompleteRotationReturn] ë³µê·€ íšŒì „ ì™„ë£Œ"));
	Super::CompleteRotationReturn();

	if (LoopType == EGimmickLoopType::PingPong && bLoopingEnabled)
	{
		if (LoopInterval > 0.f)
		{
			GetWorldTimerManager().SetTimer(LoopTimerHandle, this, &ALCAutoGimmick::HandleLoop, LoopInterval, false);
		}
		else
		{
			HandleLoop();
		}
	}
}

void ALCAutoGimmick::ReturnToInitialState_Implementation()
{
	//LOG_Art(Log, TEXT("ğŸ” [ReturnToInitialState] ë³µê·€ ì‹œì‘"));

	if (LoopType == EGimmickLoopType::PingPong)
	{
		ReturnMoveDuration = BackwardMoveDuration;
		ReturnRotationDuration = BackwardRotationDuration;
	}

	Super::ReturnToInitialState_Implementation();

	if (!HasAuthority()) return;

	StopLoop();

	if (LoopRestartDelay > 0.f && LoopType != EGimmickLoopType::None)
	{
		//LOG_Art(Log, TEXT("â³ [ReturnToInitialState] %.2fì´ˆ í›„ ë£¨í”„ ì¬ì‹œì‘ ì˜ˆì•½"), LoopRestartDelay);
		GetWorldTimerManager().SetTimer(LoopTimerHandle, this, &ALCAutoGimmick::StartLoop, LoopRestartDelay, false);
	}
}
