#include "Item/ItemSpawner.h"
#include "Character/BaseCharacter.h"
#include "Engine/World.h"
#include "Item/EquipmentItem/GunBase.h"
#include "Kismet/KismetMathLibrary.h"
#include "Components/StaticMeshComponent.h"
#include "Components/SphereComponent.h"
#include "LastCanary.h"

AItemSpawner::AItemSpawner()
{
    PrimaryActorTick.bCanEverTick = true;

    // ë£¨íŠ¸ ì»´í¬ë„ŒíŠ¸ ì„¤ì •
    RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));

    // ìŠ¤í¬ë„ˆ ë©”ì‹œ ì»´í¬ë„ŒíŠ¸ ìƒì„±
    SpawnerMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("SpawnerMesh"));
    SpawnerMesh->SetupAttachment(RootComponent);
    SpawnerMesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);

    // ê·¼ì ‘ ê°ì§€ ì»´í¬ë„ŒíŠ¸ ìƒì„±
    ProximityComponent = CreateDefaultSubobject<USphereComponent>(TEXT("ProximityComponent"));
    ProximityComponent->SetupAttachment(RootComponent);
    ProximityComponent->SetCollisionProfileName(TEXT("Trigger"));
    ProximityComponent->SetSphereRadius(500.0f);

    ProximityComponent->SetCollisionEnabled(ECollisionEnabled::NoCollision);

    // ì˜¤ë²„ë© ì´ë²¤íŠ¸ ë°”ì¸ë”©
    ProximityComponent->OnComponentBeginOverlap.AddDynamic(this, &AItemSpawner::OnProximityBeginOverlap);
    ProximityComponent->OnComponentEndOverlap.AddDynamic(this, &AItemSpawner::OnProximityEndOverlap);

    // ê¸°ë³¸ê°’ ì„¤ì •
    CurrentSpawnCount = 0;
    bIsEnabled = true;
    LastSpawnTime = 0.0f;
    bPlayerInProximity = false;

    // ë„¤íŠ¸ì›Œí¬ ë³µì œ í™œì„±í™”
    bReplicates = true;
    bAlwaysRelevant = false;
    AActor::SetReplicateMovement(false); // ìŠ¤í¬ë„ˆëŠ” ì›€ì§ì´ì§€ ì•ŠìŒ
}

void AItemSpawner::BeginPlay()
{
    Super::BeginPlay();

    // ìŠ¤í¬ë„ˆ ì„¤ì • ìƒíƒœ ì „ì²´ ë¡œê·¸
    UE_LOG(LogTemp, Warning, TEXT("=== [AItemSpawner::BeginPlay] ìŠ¤í¬ë„ˆ ì„¤ì • í™•ì¸ ì‹œì‘ ==="));
    UE_LOG(LogTemp, Warning, TEXT("ìŠ¤í¬ë„ˆ ì´ë¦„: %s"), *GetName());
    UE_LOG(LogTemp, Warning, TEXT("ìŠ¤í¬ë„ˆ íƒ€ì…: %d"), (int32)SpawnerType);
    UE_LOG(LogTemp, Warning, TEXT("ìŠ¤í° ê°€ëŠ¥í•œ ì•„ì´í…œ ê°œìˆ˜: %d"), SpawnableItems.Num());

    // ê° ì•„ì´í…œ ì •ë³´ ìƒì„¸ ë¡œê·¸
    for (int32 i = 0; i < SpawnableItems.Num(); ++i)
    {
        const FSpawnableItemInfo& ItemInfo = SpawnableItems[i];
        UE_LOG(LogTemp, Warning, TEXT("--- ì•„ì´í…œ [%d] ì •ë³´ ---"), i);
        UE_LOG(LogTemp, Warning, TEXT("ItemClass: %s"), ItemInfo.ItemClass ? *ItemInfo.ItemClass->GetName() : TEXT("NULL"));
        UE_LOG(LogTemp, Warning, TEXT("ItemRowName: %s"), *ItemInfo.ItemRowName.ToString());
        UE_LOG(LogTemp, Warning, TEXT("ItemRowName IsValid: %s"), ItemInfo.ItemRowName.IsValid() ? TEXT("True") : TEXT("False"));
        UE_LOG(LogTemp, Warning, TEXT("ItemRowName IsNone: %s"), ItemInfo.ItemRowName.IsNone() ? TEXT("True") : TEXT("False"));
        UE_LOG(LogTemp, Warning, TEXT("ItemRowName String: '%s'"), *ItemInfo.ItemRowName.ToString());
        UE_LOG(LogTemp, Warning, TEXT("SpawnProbability: %f"), ItemInfo.SpawnProbability);
        UE_LOG(LogTemp, Warning, TEXT("MinQuantity: %d"), ItemInfo.MinQuantity);
        UE_LOG(LogTemp, Warning, TEXT("MaxQuantity: %d"), ItemInfo.MaxQuantity);
        UE_LOG(LogTemp, Warning, TEXT("MinDurability: %f"), ItemInfo.MinDurability);
        UE_LOG(LogTemp, Warning, TEXT("MaxDurability: %f"), ItemInfo.MaxDurability);
    }
    UE_LOG(LogTemp, Warning, TEXT("=== ìŠ¤í¬ë„ˆ ì„¤ì • í™•ì¸ ì™„ë£Œ ==="));

    // ê·¼ì ‘ ì»´í¬ë„ŒíŠ¸ ë°˜ê²½ ì„¤ì •
    ProximityComponent->SetSphereRadius(ProximityDistance);

    // ìë™ ìŠ¤í° ì²˜ë¦¬
    if (bAutoSpawnOnStart && SpawnerType == ESpawnerType::OneTime)
    {
        SpawnItems();
    }
    else if (SpawnerType == ESpawnerType::Periodic)
    {
        GetWorldTimerManager().SetTimer(SpawnTimerHandle, this, &AItemSpawner::HandlePeriodicSpawn, SpawnInterval, true);
    }
}

void AItemSpawner::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);

    // Proximity íƒ€ì… ì²˜ë¦¬
    if (SpawnerType == ESpawnerType::Proximity && bIsEnabled)
    {
        HandleProximitySpawn();
    }
}

void AItemSpawner::SpawnItems()
{
    LOG_Item_WARNING(TEXT("[AItemSpawner::SpawnItems] ìŠ¤í° ì‹œì‘ - Authority: %s, Enabled: %s, Count: %d/%d"),
        HasAuthority() ? TEXT("True") : TEXT("False"),
        bIsEnabled ? TEXT("True") : TEXT("False"),
        CurrentSpawnCount, MaxSpawnCount);

    if (!bIsEnabled || CurrentSpawnCount >= MaxSpawnCount)
    {
        LOG_Item_WARNING(TEXT("[AItemSpawner::SpawnItems] ìŠ¤í¬ë„ˆ ë¹„í™œì„±í™” ìƒíƒœì´ê±°ë‚˜ ìµœëŒ€ ìŠ¤í° ê°œìˆ˜ì— ë„ë‹¬í–ˆìŠµë‹ˆë‹¤."));
        return;
    }

    if (SpawnableItems.Num() == 0)
    {
        LOG_Item_WARNING(TEXT("[AItemSpawner::SpawnItems] ìŠ¤í°í•  ì•„ì´í…œì´ ì„¤ì •ë˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤."));
        return;
    }

    // ì„œë²„ì—ì„œë§Œ ì‹¤í–‰
    if (!HasAuthority())
    {
        LOG_Item_WARNING(TEXT("[AItemSpawner::SpawnItems] Authority ì—†ìŒ"));
        return;
    }

    // ëœë¤ ì•„ì´í…œ ì„ íƒ
    FSpawnableItemInfo* SelectedItem = SelectRandomItem();
    if (!SelectedItem)
    {
        LOG_Item_WARNING(TEXT("[AItemSpawner::SpawnItems] ìœ íš¨í•œ ì•„ì´í…œì„ ì„ íƒí•˜ì§€ ëª»í–ˆìŠµë‹ˆë‹¤."));
        return;
    }

    // ì•„ì´í…œ ìŠ¤í°
    AItemBase* SpawnedItem = SpawnSpecificItem(*SelectedItem);
    if (SpawnedItem)
    {
        CurrentSpawnCount++;
        OnItemSpawned(SpawnedItem);

        LOG_Item_WARNING(TEXT("[AItemSpawner::SpawnItems] ì•„ì´í…œ ìŠ¤í° ì„±ê³µ: %s"),
            *SelectedItem->ItemRowName.ToString());

        // ìŠ¤í¬ë„ˆ ìˆ¨ê¸°ê¸° ì„¤ì • í™•ì¸
        if (bHideSpawnerAfterSpawn)
        {
            SpawnerMesh->SetVisibility(false);
        }

        // OneTime íƒ€ì…ì´ë©´ ë¹„í™œì„±í™”
        if (SpawnerType == ESpawnerType::OneTime)
        {
            SetSpawnerEnabled(false);
        }
    }
}

AItemBase* AItemSpawner::SpawnSpecificItem(const FSpawnableItemInfo& ItemInfo)
{
    if (!ItemInfo.ItemClass)
    {
        LOG_Item_WARNING(TEXT("[AItemSpawner::SpawnSpecificItem] ItemClassê°€ ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤."));
        return nullptr;
    }

    // ìŠ¤í° ìœ„ì¹˜ ê³„ì‚°
    FVector SpawnLocation = GetRandomSpawnLocation();
    FRotator SpawnRotation = FRotator::ZeroRotator;

    // ì•„ì´í…œ ìŠ¤í°
    FActorSpawnParameters SpawnParams;
    SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButDontSpawnIfColliding;
    SpawnParams.Owner = this;

    AItemBase* SpawnedItem = GetWorld()->SpawnActor<AItemBase>(ItemInfo.ItemClass, SpawnLocation, SpawnRotation, SpawnParams);

    if (SpawnedItem)
    {
        // ğŸ”¥ ì¤‘ìš”: ì†ì„± ì„¤ì • ìˆœì„œ
        SpawnedItem->SetReplicates(true);
        SpawnedItem->SetReplicateMovement(true);
        SpawnedItem->bAlwaysRelevant = true;

        // ğŸ”¥ ItemRowNameì„ ë¨¼ì € ì„¤ì • (OnRep íŠ¸ë¦¬ê±°)
        SpawnedItem->ItemRowName = ItemInfo.ItemRowName;

        // ë‹¤ë¥¸ ì†ì„±ë“¤ ì„¤ì •
        SpawnedItem->Quantity = FMath::RandRange(ItemInfo.MinQuantity, ItemInfo.MaxQuantity);
        SpawnedItem->Durability = FMath::RandRange(ItemInfo.MinDurability, ItemInfo.MaxDurability);

        // ì„œë²„ì—ì„œ ë°ì´í„° ì ìš©
        SpawnedItem->ApplyItemDataFromTable();

        // ì´ê¸° íŠ¹í™” ì²˜ë¦¬
        if (AGunBase* Gun = Cast<AGunBase>(SpawnedItem))
        {
            Gun->ApplyGunDataFromDataTable();
        }

        // ë„¤íŠ¸ì›Œí¬ ì—…ë°ì´íŠ¸
        SpawnedItem->ForceNetUpdate();

        LOG_Item_WARNING(TEXT("[ItemSpawner::SpawnSpecificItem] ì•„ì´í…œ ìŠ¤í° ì™„ë£Œ: %s (Q:%d, D:%.1f)"),
            *ItemInfo.ItemRowName.ToString(), SpawnedItem->Quantity, SpawnedItem->Durability);
    }

    return SpawnedItem;
}

void AItemSpawner::ApplyDelayedItemProperties(AItemBase* Item, const FSpawnableItemInfo& ItemInfo)
{
    if (!IsValid(Item))
    {
        LOG_Item_WARNING(TEXT("[AItemSpawner::ApplyDelayedItemProperties] Itemì´ ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤."));
        return;
    }

    LOG_Item_WARNING(TEXT("[AItemSpawner::ApplyDelayedItemProperties] ì§€ì—° ì†ì„± ì ìš© ì‹œì‘ - RowName: %s"),
        *ItemInfo.ItemRowName.ToString());

    // 1. ê¸°ë³¸ ì†ì„± ì„¤ì •
    Item->ItemRowName = ItemInfo.ItemRowName;

    // 2. ìˆ˜ëŸ‰ ì„¤ì •
    int32 Quantity = FMath::RandRange(ItemInfo.MinQuantity, ItemInfo.MaxQuantity);
    Item->Quantity = Quantity;

    // 3. ë‚´êµ¬ë„ ì„¤ì •
    float Durability = FMath::RandRange(ItemInfo.MinDurability, ItemInfo.MaxDurability);
    Item->Durability = Durability;

    // 4. ë„¤íŠ¸ì›Œí¬ ë³µì œ ê°•ì œ ì—…ë°ì´íŠ¸ (ì„œë²„ì—ì„œë§Œ)
    if (GetNetMode() != NM_Client)
    {
        Item->ForceNetUpdate();
    }

    LOG_Item_WARNING(TEXT("[AItemSpawner::ApplyDelayedItemProperties] ê¸°ë³¸ ì†ì„± ì„¤ì • ì™„ë£Œ - RowName: %s, ìˆ˜ëŸ‰: %d, ë‚´êµ¬ë„: %.1f"),
        *ItemInfo.ItemRowName.ToString(), Quantity, Durability);

    // 5. ë°ì´í„° í…Œì´ë¸” ì ìš© (ì¶”ê°€ ì§€ì—°)
    FTimerHandle DataTableDelayHandle;
    GetWorld()->GetTimerManager().SetTimer(DataTableDelayHandle,
        [Item]()
        {
            if (IsValid(Item))
            {
                Item->ApplyItemDataFromTable();

                // GunBaseì¸ ê²½ìš° ì¶”ê°€ ì²˜ë¦¬
                if (AGunBase* Gun = Cast<AGunBase>(Item))
                {
                    Gun->ApplyGunDataFromDataTable();
                }
            }
        },
        0.5f, false);
}

void AItemSpawner::ResetSpawner()
{
    CurrentSpawnCount = 0;
    bIsEnabled = true;
    SpawnerMesh->SetVisibility(true);

    // íƒ€ì´ë¨¸ ì¬ì‹œì‘
    if (SpawnerType == ESpawnerType::Periodic)
    {
        GetWorldTimerManager().SetTimer(SpawnTimerHandle, this, &AItemSpawner::HandlePeriodicSpawn, SpawnInterval, true);
    }

    LOG_Item_WARNING(TEXT("[AItemSpawner::ResetSpawner] ìŠ¤í¬ë„ˆê°€ ë¦¬ì…‹ë˜ì—ˆìŠµë‹ˆë‹¤."));
}

void AItemSpawner::SetSpawnerEnabled(bool bEnabled)
{
    bIsEnabled = bEnabled;

    if (!bEnabled)
    {
        GetWorldTimerManager().ClearTimer(SpawnTimerHandle);
        OnSpawnerDeactivated();
    }
    else if (SpawnerType == ESpawnerType::Periodic)
    {
        GetWorldTimerManager().SetTimer(SpawnTimerHandle, this, &AItemSpawner::HandlePeriodicSpawn, SpawnInterval, true);
    }
}

void AItemSpawner::HandlePeriodicSpawn()
{
    if (bIsEnabled && CurrentSpawnCount < MaxSpawnCount)
    {
        SpawnItems();
    }
}

void AItemSpawner::HandleProximitySpawn()
{
    if (bPlayerInProximity && bIsEnabled && CurrentSpawnCount < MaxSpawnCount)
    {
        float CurrentTime = GetWorld()->GetTimeSeconds();
        if (CurrentTime - LastSpawnTime >= SpawnInterval)
        {
            SpawnItems();
            LastSpawnTime = CurrentTime;
        }
    }
}

FVector AItemSpawner::GetRandomSpawnLocation()
{
    FVector BaseLocation = GetActorLocation();

    if (SpawnRadius > 0.0f)
    {
        FVector RandomOffset = UKismetMathLibrary::RandomUnitVector() * FMath::RandRange(0.0f, SpawnRadius);
        RandomOffset.Z = 0.0f; // Zì¶•ì€ ê³ ì •
        return BaseLocation + RandomOffset;
    }

    return BaseLocation;
}

FSpawnableItemInfo* AItemSpawner::SelectRandomItem()
{
    if (SpawnableItems.Num() == 0)
    {
        return nullptr;
    }

    // í™•ë¥  ê¸°ë°˜ ì„ íƒ
    float TotalProbability = 0.0f;
    for (const FSpawnableItemInfo& Item : SpawnableItems)
    {
        TotalProbability += Item.SpawnProbability;
    }

    if (TotalProbability <= 0.0f)
    {
        return nullptr;
    }

    float RandomValue = FMath::RandRange(0.0f, TotalProbability);
    float AccumulatedProbability = 0.0f;

    for (FSpawnableItemInfo& Item : SpawnableItems)
    {
        AccumulatedProbability += Item.SpawnProbability;
        if (RandomValue <= AccumulatedProbability)
        {
            return &Item;
        }
    }

    // í´ë°±: ì²« ë²ˆì§¸ ì•„ì´í…œ ë°˜í™˜
    return &SpawnableItems[0];
}

void AItemSpawner::OnProximityBeginOverlap(UPrimitiveComponent* OverlappedComp, AActor* OtherActor,
    UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
    ABaseCharacter* Player = Cast<ABaseCharacter>(OtherActor);
    if (Player && Player->OwnedTags.HasTagExact(FGameplayTag::RequestGameplayTag(FName("Character.Player"))))
    {
        bPlayerInProximity = true;
        LOG_Item_WARNING(TEXT("[AItemSpawner::OnProximityBeginOverlap] í”Œë ˆì´ì–´ê°€ ê·¼ì ‘í–ˆìŠµë‹ˆë‹¤."));
    }
}

void AItemSpawner::OnProximityEndOverlap(UPrimitiveComponent* OverlappedComp, AActor* OtherActor,
    UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
    ABaseCharacter* Player = Cast<ABaseCharacter>(OtherActor);
    if (Player && Player->OwnedTags.HasTagExact(FGameplayTag::RequestGameplayTag(FName("Character.Player"))))
    {
        bPlayerInProximity = false;
        LOG_Item_WARNING(TEXT("[AItemSpawner::OnProximityEndOverlap] í”Œë ˆì´ì–´ê°€ ë©€ì–´ì¡ŒìŠµë‹ˆë‹¤."));
    }
}

#if WITH_EDITOR
void AItemSpawner::PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent)
{
    Super::PostEditChangeProperty(PropertyChangedEvent);

    static const FName ProximityDistancePropName = GET_MEMBER_NAME_CHECKED(AItemSpawner, ProximityDistance);

    if (PropertyChangedEvent.Property && PropertyChangedEvent.Property->GetFName() == ProximityDistancePropName)
    {
        if (ProximityComponent)
        {
            ProximityComponent->SetSphereRadius(ProximityDistance);
        }
    }
}
#endif
